function [infa, infb] = refpaninf(del,xm,ym)
ym = ym + 1e-8; % Make sure no div/0 happens
xmd = xm - del;
I0 = -(1 / (4 .* pi)) .* ...
    (xm.*log(xm.*xm + ym.*ym) - xmd.*log(xmd.*xmd + ym.*ym) ...
    - 2 .* del + 2 .* ym.*(atan(xm./ym) - atan(xmd./ym)));
I1 = (1 / (8 .* pi)) .* ...
    ((xm.*xm + ym.*ym).*log(xm.*xm + ym.*ym) - ...
    (xmd.*xmd + ym.*ym).*log(xmd.*xmd + ym.*ym) ...
    - 2 .* xm.*del + del.*del);
infa = (1 - xm./del) .* I0 - I1./del;
infb = (xm./del) .* I0 + I1./del;
end