function [xk yk] = parsec(param)
    rle = param(1);
    x_low = param(2);
    y_low = param(3);
    d2ydx2_low = param(4);
    th_low = param(5);
    x_up = param(6);
    y_up = param(7);
    d2ydx2_up = param(8);
    th_up = param(9);
    % https://github.com/dqsis/parsec-airfoils/blob/master/parseccoef.py
    % Find the lower coefficients
    coef = zeros([6, 1]);
    coef(1) = -sqrt(2 * rle);
    
    xle = 0.0;
    yle = 0.0;
    xte = 1.0;
    yte = 0.0;

    x_cre = x_low;
    y_cre = y_low;
    th_cre = th_low;
    d2ydx2_cre = d2ydx2_low;
    
    A = [xte.^1.5, xte.^2.5, xte.^3.5, xte.^4.5, xte.^5.5; ...
         x_cre.^1.5, x_cre.^2.5, x_cre.^3.5, x_cre.^4.5, ...
          x_cre.^5.5; ...
         1.5*sqrt(xte), 2.5*xte.^1.5, 3.5*xte.^2.5, ...
          4.5*xte.^3.5, 5.5*xte.^4.5; ...
         1.5*sqrt(x_cre), 2.5*x_cre.^1.5, 3.5*x_cre.^2.5, ...
          4.5*x_cre.^3.5, 5.5*x_cre.^4.5; ...
         0.75*(1/sqrt(x_cre)), 3.75*sqrt(x_cre), 8.75*x_cre.^1.5, ...
          15.75*x_cre.^2.5, 24.75*x_cre.^3.5];

    B = [yte - coef(1)*sqrt(xte), ...
         y_cre - coef(1)*sqrt(x_cre), ...
         tan(th_cre*pi/180) - 0.5*coef(1)*(1/sqrt(xte)), ...
         -0.5*coef(1)*(1/sqrt(x_cre)), ...
         d2ydx2_cre + 0.25*coef(1)*x_cre.^(-1.5)]';

    asdf = A\B;
    coef(2:end) = asdf;

    xs_low = linspace(xte, xle, 401);
    ys_low = (coef(1)*xs_low.^(1/2) + ...
              coef(2)*xs_low.^(3/2) + ...
              coef(3)*xs_low.^(5/2) + ...
              coef(4)*xs_low.^(7/2) + ...
              coef(5)*xs_low.^(9/2) + ...
              coef(6)*xs_low.^(11/2));

    coef(1) = sqrt(2 * rle);
    
    x_cre = x_up;
    y_cre = y_up;
    th_cre = th_up;
    d2ydx2_cre = d2ydx2_up;
    
    A = [xte.^1.5, xte.^2.5, xte.^3.5, xte.^4.5, xte.^5.5; ...
         x_cre.^1.5, x_cre.^2.5, x_cre.^3.5, x_cre.^4.5, ...
          x_cre.^5.5; ...
         1.5*sqrt(xte), 2.5*xte.^1.5, 3.5*xte.^2.5, ...
          4.5*xte.^3.5, 5.5*xte.^4.5; ...
         1.5*sqrt(x_cre), 2.5*x_cre.^1.5, 3.5*x_cre.^2.5, ...
          4.5*x_cre.^3.5, 5.5*x_cre.^4.5; ...
         0.75*(1/sqrt(x_cre)), 3.75*sqrt(x_cre), 8.75*x_cre.^1.5, ...
          15.75*x_cre.^2.5, 24.75*x_cre.^3.5];

    B = [yte - coef(1)*sqrt(xte), ...
         y_cre - coef(1)*sqrt(x_cre), ...
         tan(th_cre*pi/180) - 0.5*coef(1)*(1/sqrt(xte)), ...
         -0.5*coef(1)*(1/sqrt(x_cre)), ...
         d2ydx2_cre + 0.25*coef(1)*x_cre.^(-1.5)]';

    asdf = A\B;
    coef(2:end) = asdf;

    xs_up = linspace(xle, xte, 401);
    xs_up(1) = [];
    ys_up =  (coef(1)*xs_up.^(1/2) + ...
              coef(2)*xs_up.^(3/2) + ...
              coef(3)*xs_up.^(5/2) + ...
              coef(4)*xs_up.^(7/2) + ...
              coef(5)*xs_up.^(9/2) + ...
              coef(6)*xs_up.^(11/2));
    
    xk = zeros([length(xs_low) + length(xs_up), 1]);
    yk = xk;
    xk(1:length(xs_low)) = xs_low;
    xk(length(xs_low) + 1:end) = xs_up;
    yk(1:length(xs_low)) = ys_low;
    yk(length(xs_low) + 1:end) = ys_up;

    fname = ['Geometry/parsec.surf'];
    
    fid = fopen(fname,'w');
    fprintf ( fid, '%10.6f %10.6f \n', [xk';yk'] );
    fclose(fid);
end
    